import { AddressService } from './address/address.service';
import { AuthService } from './auth/auth.service';
import { CartService } from './cart/cart.service';
import { CategoryService } from './category/category.service';
import { CountryService } from './country/country.service';
import { ModerationService } from './moderation/moderation.service';
import { OrderService } from './order/order.service';
import { PasswordService } from './password/password.service';
import { ProductService } from './product/product.service';
import { ReviewService } from './review/review.service';
import { StorageService } from './storage/supabase.service';
import { UserService } from './user/user.service';
import { WishedItemService } from './wished/wished.service';

export const passwordService = new PasswordService();
export const countryService = new CountryService();
export const storageService = new StorageService();
export const productService = new ProductService(storageService);
export const cartService = new CartService(productService);
export const userService = new UserService(passwordService);
export const authService = new AuthService(userService, passwordService);
export const categoryService = new CategoryService();
export const wishedItemService = new WishedItemService();
export const addressService = new AddressService();
export const orderService = new OrderService();
export const reviewService = new ReviewService();
export const moderationService = new ModerationService();
