import './globals.css';
import type { Metadata } from 'next';
import AuthProviders from '@/components/providers/AuthProviders';

export const metadata: Metadata = {
  title: 'eCommerce Next',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-neutral-50">
        <AuthProviders>
          <main className="w-screen h-screen ">{children}</main>
        </AuthProviders>
      </body>
    </html>
  );
}
